### ISSUE TITLE
Add support for Web

### ISSUE THREAD

**Issue by terrakok** [mori-atsushi/insetsx#37]
Please add support for insetsx Web platform. It would enough to make it the same as on the Desktop target: simple zero paddings.

**Comment by mori-atsushi** [comment]
I am not familiar with it, but there is a safe area in iOS safari.
https://developer.mozilla.org/en-US/docs/Web/CSS/env

**Comment by mori-atsushi** [comment]
Also, Compose web is available for HTML and wasm.

**Comment by terrakok** [comment]
I guess for the first iteration, it is enough to just have a zero paddings

**Comment by terrakok** [comment]
I added the library to my web wizard 😉 
https://terrakok.github.io/Compose-Multiplatform-Wizard/
