### ISSUE TITLE
Light status bar color bug

### ISSUE THREAD

**Issue by maltsev-gorskij** [mori-atsushi/insetsx#55]
Looks like i stumbled upon bug when setting StatusBar color to white
```
val windowInsetsController = rememberWindowInsetsController()
LaunchedEffect(Unit) {
    windowInsetsController?.apply {
        setStatusBarContentColor(dark = false)
        setNavigationBarsContentColor(dark = false)
    }
}
```

On Android build everything is fine. In iOS simulator, when i use dark = false, status bar dissapearing.
![image](https://github.com/mori-atsushi/insetsx/assets/55731252/3ca4b4a2-be27-4804-a2d3-7be4e330dc7c)

I tried to use
`setIsStatusBarsVisible(true)`

and it worked and StatusBar is visible again. 
![image](https://github.com/mori-atsushi/insetsx/assets/55731252/9f242a7e-f776-4452-bbca-ea65bc037c82)

So for Light colors this config must be used, which is looks like bug. 
```
    val windowInsetsController = rememberWindowInsetsController()
    LaunchedEffect(Unit) {
        windowInsetsController?.apply {
            setStatusBarContentColor(dark = false)
            setNavigationBarsContentColor(dark = false)
            setIsStatusBarsVisible(true)
        }
    }
```

**Comment by mori-atsushi** [comment]
Thank you for your report. I have released a fixed version, v0.1.0-alpha08.
https://github.com/mori-atsushi/insetsx/releases/tag/v0.1.0-alpha08
